name: plantapp
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  animated_notch_bottom_bar: ^1.0.0
  flutter_svg: ^2.0.7
  english_words: ^4.0.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.0
  uuid: ^3.0.6
  permission_handler: ^10.2.0
  navbar_router: ^0.7.4
  convex_bottom_bar: ^3.0.0
  windows_notification: ^1.2.0
  path_provider: ^2.0.0
  http: ^0.13.3
  image_picker: ^0.8.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/favipng.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/favipng.png
